# Generated by Django 3.0.1 on 2020-01-05 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puples',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('surname', models.TextField(verbose_name='Фамилия')),
                ('rate', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='puples_photo')),
                ('url', models.SlugField(default='404', max_length=160)),
            ],
            options={
                'verbose_name': 'Учениики',
                'verbose_name_plural': 'Учениики',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название мероприятия')),
                ('organization', models.TextField(verbose_name='Название организации')),
                ('date', models.DateField(verbose_name='Дата посещения')),
                ('events', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Puples', verbose_name='Мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
