# Generated by Django 3.0.1 on 2020-01-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puples',
            name='url',
        ),
    ]
