# Generated by Django 3.0.1 on 2020-01-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_puples_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puples',
            name='image',
            field=models.ImageField(blank=True, default='static/images/white.png', upload_to='puples_photo'),
        ),
    ]
