# Generated by Django 3.0.1 on 2020-01-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200105_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puples',
            options={'verbose_name': 'Ученики', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterField(
            model_name='puples',
            name='image',
            field=models.ImageField(blank=True, default='puples_photo/user-2.png', upload_to='puples_photo'),
        ),
    ]
