# Generated by Django 3.0.1 on 2020-01-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200105_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
