# Generated by Django 2.2.5 on 2020-01-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_puples_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='verification_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
