# Generated by Django 2.2.5 on 2020-01-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_events_verification_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='verification_file',
            field=models.FileField(null=True, upload_to='verification_files/'),
        ),
    ]
