# Generated by Django 3.0.1 on 2020-01-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20200111_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(verbose_name='Название темы')),
                ('name', models.TextField(verbose_name='Название работы')),
                ('result', models.FileField(null=True, upload_to='result_puples')),
            ],
            options={
                'verbose_name': 'Работы учеников',
                'verbose_name_plural': 'Работы учеников',
            },
        ),
    ]
