# Generated by Django 3.0.1 on 2020-01-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='result',
            field=models.FileField(null=True, upload_to='result_puples', verbose_name='Результат'),
        ),
    ]
