# Generated by Django 3.0.1 on 2020-01-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20200114_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
    ]
