# Generated by Django 3.0.1 on 2020-01-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_works_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='result',
            field=models.URLField(null=True, verbose_name='Результат'),
        ),
    ]
