# Generated by Django 3.0.1 on 2020-01-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20200116_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='result',
            field=models.TextField(null=True, verbose_name='Результат'),
        ),
    ]
