# Generated by Django 3.0.1 on 2020-01-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20200116_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puples',
            name='name',
            field=models.TextField(null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='puples',
            name='surname',
            field=models.TextField(null=True, verbose_name='Фамилия'),
        ),
    ]
