# Generated by Django 3.0.1 on 2020-02-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20200117_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_rate',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='events',
            name='organization',
            field=models.CharField(max_length=300, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='events',
            name='verification_file',
            field=models.FileField(null=True, upload_to='verification_files/', verbose_name='Файл'),
        ),
    ]
