# Generated by Django 3.0.1 on 2020-03-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20200219_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('name_task', models.CharField(max_length=200, verbose_name='Название задачи')),
                ('discription_task', models.TextField(verbose_name='Описание задачи')),
                ('result', models.TextField(null=True, verbose_name='Результат')),
            ],
            options={
                'verbose_name': 'Задача дня',
                'verbose_name_plural': 'Задача дня',
            },
        ),
    ]
