# Generated by Django 3.0.1 on 2020-03-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_daystask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystask',
            name='result',
            field=models.CharField(max_length=200, null=True, verbose_name='Результат'),
        ),
    ]
