# Generated by Django 3.0.1 on 2020-03-24 17:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20200324_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daystask',
            name='discription_task',
            field=tinymce.models.HTMLField(verbose_name='Описание задачи'),
        ),
    ]
