# Generated by Django 3.0.1 on 2020-03-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_daystask_count_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='daystask',
            name='id_answers',
            field=models.CharField(default='', max_length=200, verbose_name='ID учеников, кто дал правильный ответ'),
        ),
        migrations.AlterField(
            model_name='daystask',
            name='count_answer',
            field=models.IntegerField(default=0, verbose_name='Количество человек, которые могут решить задачу (указать отрицательное число)'),
        ),
    ]
